version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: gestao_financeira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Yonebayashi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # porta para conexão da aplicação
      - "15672:15672"  # painel web
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
